### ISSUE TITLE
[Feature Request] add fs.writeFile(path, File) support

### ISSUE THREAD

**Issue by deepkolos** [StarLederer/vite-plugin-fs#19] opened 2023-10-11 03:36 UTC
current fs.writeFile support String only

PR https://github.com/StarLederer/vite-plugin-fs/pull/20

**Comment by StarLederer** [comment] 2023-10-11 09:27
I agree with the cause and will take a look at the PR. Thank you very much for your interest!

**Comment by StarLederer** [comment] 2023-10-28 15:48
#20 merged. Thank you once again for your help!

**Closed by StarLederer** 2023-10-28 15:48 UTC
